### ISSUE TITLE
Gnote is automatically deleting informatio in notes entered during editing

### ISSUE THREAD

**Issue by yupthatguy** [lelutin/scout#35]
I have a rather odd situation. It doesn't matter if it is a previously saved note or a new note, while I am editing a note, if I switch active windows in Ubuntu 18.04, Gnote will delete the most recent information that I typed into the note. I am using Gnote 3.28.0. As you can imagine, needing to re-type my note if I switch windows, gets annoying quickly.. any thoughts on how to fix this bug?

**Comment by lelutin** [comment]
wow that is odd...

when you say that you're switching active window, do you mean that your were in the editor that gets spawned by scout and then going to another window?

**Comment by yupthatguy** [comment]
Actually, I think the issue may be with the "autosave" , it seems to be more timer related that windows...  exactly a minute after I stop editing a note the content I most recently entered will literally disappear, but not consistently... 

when content does disappear, its a minute after I stop typing

As a workaround, I have been using " < " as a save button   (though irrlevant now, what I meant by active window is active application windows that I have open, but now I think the problem is more time related)

**Comment by lelutin** [comment]
I'm still not super certain what is concerned by the problem here: the "edit" action from scout only modifies a note when the user saves and quits the editor.

Are you having issues with gnote itself (e.g. editing content directly in gnote) or with scout's edit subcommand? If your issues are with using gnote directly, is it somehow related to the CLI interface? Please describe a bit more of what happens and in which application until you see the problem.

For what it's worth, this projet is a CLI interface to tomboy and gnote which uses their dbus interfaces. If the bug is strictly with gnote I won't be able to help. But if your problem happens specifically when using the CLI interface then maybe we can find out more by narrating the issue a bit more.

**Comment by yupthatguy** [comment]
I profusely apologize... apparently I have been "barking up the wrong tree" wasting both of our time... (I should have know something was amiss when you kept saying scout :-/  my bad... I will find the correct github issues page...

**Comment by lelutin** [comment]
> I profusely apologize... apparently I have been "barking up the wrong tree" wasting both of our time... (I should have know something was amiss when you kept saying scout :-/ my bad... I will find the correct github issues page...

no problem! I'm glad that things are now clearer and you can get better help about this problem (which does sound quite annoying)

My guess is you could either report the bug on gnote's repository directly https://gitlab.gnome.org/GNOME/gnote/-/issues

or you could open a bug report against the gnote package on Ubuntu https://help.ubuntu.com/community/ReportingBugs -- apparently nowadays there's a command named "ubuntu-bug" which you can call via the "Run command" interface.
