### ISSUE TITLE
Build fails with InvalidVersion

### ISSUE THREAD

**Issue by bunder** [lelutin/scout#42]
Build fails with following error:

```
$ python setup.py
Traceback (most recent call last):
  File ".../setup.py", line 49, in <module>
    setup(
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 314, in __init__
    self.metadata.version = self._normalize_version(self.metadata.version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 350, in _normalize_version
    normalized = str(Version(version))
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.4-42-g0ceb148'
```

**Comment by lelutin** [comment]
@bunder wow thanks for reporting this issue (and sorry for responding only 4 months later :\ ) . Do you use scout yourself or are you wishing to use it?

I've pushed to master a switch from `setup.py` to `pyproject.toml` along with a replacement of the current method for generating the version string to what I found pytest was doing: just using `setuptools_scm` to auto-generate that. Hopefully that can make it possible to install now with `pip install .` or `pip install -e .`

After installing, I'm not entirely confident that the code is working great since the test suite is currently broken. nosetests fails to run and the way it fails tells me that nose itself is just entirely deprecated..

I'll close this issue since I think the install issue should be fixed, but don't hesitate to reopen or comment if you still have issues. And if you wish to use the codebase and stumble upon stuff that's broken, I'll be happy to help out if you open another issue.

Cheers!
